POST http://localhost:5000/api/user/register
Content-Type: application/json

{
	"firstName": "jon",
	"lastName": "doe",
	"email": "jon2@gmfai3dlf.com",
	"password": "password",
	"birthday": "1996-12-31",
	"profession": "developer",
	"phone": 1234567,
	"gender": "male",
	"degree": "software engineering",
	"descriptionOfEntrepreneurship": "very good worker"
}