PUT http://localhost:5000/api/user/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI5NzgyNTk4LCJleHAiOjE2MzAzODczOTh9.pD4nxiGNzYEpOKDs9BUFUGSd1zYtcVgsYKlGiLn4TZQ

{
	"firstName": "jon",
	"lastName": "snow",
	"email":"jonsnow@targaryan.com",
	"password": "stark"
}